name: Java CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 11.0.15
          distribution: microsoft
          
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5

      - name: Build and Test
        run: |
          mvn clean install

      - name: Publish package
        if: success()
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
