name: Java CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 14
          distribution: microsoft

      - name: Build and Test
        run: |
          ./mvnw clean install

      - name: Publish package
        if: success()
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
